### ISSUE TITLE
ProtocolLib incompatibility

### ISSUE THREAD

**Issue by Shyrogan** [MineWeb/ServerBridge#9]
Plugin cannot be run with ProtocolLib

```
[00:02:17] [Server thread/ERROR]: Could not load 'plugins/ProtocolLib.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:123) ~[minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at com.comphenix.protocol.ProtocolLib.<init>(ProtocolLib.java:65) ~[?:?]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:584) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:126) ~[minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at fr.vmarchaud.mineweb.bukkit.BukkitCore.<init>(BukkitCore.java:72) ~[?:?]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:584) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[minecraft_server.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
```

**Comment by Shyrogan** [comment]
#10

**Comment by MaximeMichaud** [comment]
Donc (https://github.com/MineWeb/ServerBridge/pull/10), réglerait le problème avec ProtocolLib?
Ou du moins, il y aurait une erreur adaptée, car le plugin regarderait si ProtocolLib est présent ?
Et cela nécessiterait que cela soit testé afin de confirmer. & de close l'issue ? Right
@Shyrogan

**Comment by Shyrogan** [comment]
> 
> 
> Donc (#10), réglerait le problème avec ProtocolLib?
> Ou du moins, il y aurait une erreur adaptée, car le plugin regarderait si ProtocolLib est présent ?
> Et cela nécessiterait que cela soit testé afin de confirmer. & de close l'issue ? Right
> @Shyrogan

Potentiellement, il faut que ce soit tester et qu'on me prévient en cas de problème.

**Comment by MaximeMichaud** [comment]
Je vais tester ça dès que je peux.
À moins que quelqu'un dans la capacité le fasse :)
